# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_engine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='search_engine.proto',
  package='nlm_search_engine',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13search_engine.proto\x12\x11nlm_search_engine\x1a\x1bgoogle/protobuf/empty.proto\"\x8f\x01\n\x14GetCandidatesRequest\x12\x11\n\ttemplates\x18\x01 \x03(\t\x12\x11\n\tquestions\x18\x02 \x03(\t\x12\x0f\n\x07headers\x18\x03 \x03(\t\x12\x15\n\rworkspace_idx\x18\x04 \x01(\t\x12\x10\n\x08\x66ile_idx\x18\x05 \x01(\t\x12\x17\n\x0fmatches_per_doc\x18\x06 \x01(\x05\"+\n\x12\x43reateIndexRequest\x12\x15\n\rworkspace_idx\x18\x01 \x01(\t\"<\n\x11\x41\x64\x64ToIndexRequest\x12\x15\n\rworkspace_idx\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_idx\x18\x02 \x01(\t\"\xd0\x01\n\tCandidate\x12\x11\n\tmatch_idx\x18\x01 \x01(\x05\x12\x10\n\x08\x66ile_idx\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x13\n\x0bheader_text\x18\x04 \x01(\t\x12\x14\n\x0cis_table_row\x18\x05 \x01(\x08\x12\r\n\x05level\x18\x06 \x01(\t\x12\x18\n\x10header_match_idx\x18\x07 \x01(\x05\x12\x12\n\nblock_type\x18\t \x01(\t\x12\x0c\n\x04\x62m25\x18\n \x01(\x02\x12\x0b\n\x03sif\x18\x0b \x01(\x02\x12\r\n\x05score\x18\x0c \x01(\x02\"E\n\x11\x43\x61ndidateResponse\x12\x30\n\ncandidates\x18\x01 \x03(\x0b\x32\x1c.nlm_search_engine.Candidate2\xf5\x02\n\x0cSearchEngine\x12[\n\x0eget_candidates\x12\'.nlm_search_engine.GetCandidatesRequest\x1a\x1c.nlm_search_engine.Candidate\"\x00\x30\x01\x12g\n\x14\x61sync_get_candidates\x12\'.nlm_search_engine.GetCandidatesRequest\x1a$.nlm_search_engine.CandidateResponse\"\x00\x12O\n\x0c\x63reate_index\x12%.nlm_search_engine.CreateIndexRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n\x0c\x61\x64\x64_to_index\x12$.nlm_search_engine.AddToIndexRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_GETCANDIDATESREQUEST = _descriptor.Descriptor(
  name='GetCandidatesRequest',
  full_name='nlm_search_engine.GetCandidatesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='templates', full_name='nlm_search_engine.GetCandidatesRequest.templates', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='questions', full_name='nlm_search_engine.GetCandidatesRequest.questions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='nlm_search_engine.GetCandidatesRequest.headers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workspace_idx', full_name='nlm_search_engine.GetCandidatesRequest.workspace_idx', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_idx', full_name='nlm_search_engine.GetCandidatesRequest.file_idx', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matches_per_doc', full_name='nlm_search_engine.GetCandidatesRequest.matches_per_doc', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=215,
)


_CREATEINDEXREQUEST = _descriptor.Descriptor(
  name='CreateIndexRequest',
  full_name='nlm_search_engine.CreateIndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_idx', full_name='nlm_search_engine.CreateIndexRequest.workspace_idx', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=260,
)


_ADDTOINDEXREQUEST = _descriptor.Descriptor(
  name='AddToIndexRequest',
  full_name='nlm_search_engine.AddToIndexRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspace_idx', full_name='nlm_search_engine.AddToIndexRequest.workspace_idx', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_idx', full_name='nlm_search_engine.AddToIndexRequest.file_idx', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=322,
)


_CANDIDATE = _descriptor.Descriptor(
  name='Candidate',
  full_name='nlm_search_engine.Candidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_idx', full_name='nlm_search_engine.Candidate.match_idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_idx', full_name='nlm_search_engine.Candidate.file_idx', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nlm_search_engine.Candidate.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header_text', full_name='nlm_search_engine.Candidate.header_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_table_row', full_name='nlm_search_engine.Candidate.is_table_row', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='nlm_search_engine.Candidate.level', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header_match_idx', full_name='nlm_search_engine.Candidate.header_match_idx', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_type', full_name='nlm_search_engine.Candidate.block_type', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bm25', full_name='nlm_search_engine.Candidate.bm25', index=8,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sif', full_name='nlm_search_engine.Candidate.sif', index=9,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='nlm_search_engine.Candidate.score', index=10,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=533,
)


_CANDIDATERESPONSE = _descriptor.Descriptor(
  name='CandidateResponse',
  full_name='nlm_search_engine.CandidateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candidates', full_name='nlm_search_engine.CandidateResponse.candidates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=535,
  serialized_end=604,
)

_CANDIDATERESPONSE.fields_by_name['candidates'].message_type = _CANDIDATE
DESCRIPTOR.message_types_by_name['GetCandidatesRequest'] = _GETCANDIDATESREQUEST
DESCRIPTOR.message_types_by_name['CreateIndexRequest'] = _CREATEINDEXREQUEST
DESCRIPTOR.message_types_by_name['AddToIndexRequest'] = _ADDTOINDEXREQUEST
DESCRIPTOR.message_types_by_name['Candidate'] = _CANDIDATE
DESCRIPTOR.message_types_by_name['CandidateResponse'] = _CANDIDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCandidatesRequest = _reflection.GeneratedProtocolMessageType('GetCandidatesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCANDIDATESREQUEST,
  '__module__' : 'search_engine_pb2'
  # @@protoc_insertion_point(class_scope:nlm_search_engine.GetCandidatesRequest)
  })
_sym_db.RegisterMessage(GetCandidatesRequest)

CreateIndexRequest = _reflection.GeneratedProtocolMessageType('CreateIndexRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINDEXREQUEST,
  '__module__' : 'search_engine_pb2'
  # @@protoc_insertion_point(class_scope:nlm_search_engine.CreateIndexRequest)
  })
_sym_db.RegisterMessage(CreateIndexRequest)

AddToIndexRequest = _reflection.GeneratedProtocolMessageType('AddToIndexRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDTOINDEXREQUEST,
  '__module__' : 'search_engine_pb2'
  # @@protoc_insertion_point(class_scope:nlm_search_engine.AddToIndexRequest)
  })
_sym_db.RegisterMessage(AddToIndexRequest)

Candidate = _reflection.GeneratedProtocolMessageType('Candidate', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATE,
  '__module__' : 'search_engine_pb2'
  # @@protoc_insertion_point(class_scope:nlm_search_engine.Candidate)
  })
_sym_db.RegisterMessage(Candidate)

CandidateResponse = _reflection.GeneratedProtocolMessageType('CandidateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CANDIDATERESPONSE,
  '__module__' : 'search_engine_pb2'
  # @@protoc_insertion_point(class_scope:nlm_search_engine.CandidateResponse)
  })
_sym_db.RegisterMessage(CandidateResponse)



_SEARCHENGINE = _descriptor.ServiceDescriptor(
  name='SearchEngine',
  full_name='nlm_search_engine.SearchEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=607,
  serialized_end=980,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_candidates',
    full_name='nlm_search_engine.SearchEngine.get_candidates',
    index=0,
    containing_service=None,
    input_type=_GETCANDIDATESREQUEST,
    output_type=_CANDIDATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='async_get_candidates',
    full_name='nlm_search_engine.SearchEngine.async_get_candidates',
    index=1,
    containing_service=None,
    input_type=_GETCANDIDATESREQUEST,
    output_type=_CANDIDATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='create_index',
    full_name='nlm_search_engine.SearchEngine.create_index',
    index=2,
    containing_service=None,
    input_type=_CREATEINDEXREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='add_to_index',
    full_name='nlm_search_engine.SearchEngine.add_to_index',
    index=3,
    containing_service=None,
    input_type=_ADDTOINDEXREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEARCHENGINE)

DESCRIPTOR.services_by_name['SearchEngine'] = _SEARCHENGINE

# @@protoc_insertion_point(module_scope)
